Return-Path: <devicetree+bounces-289372-lists+devicetree=lfdr.de@vger.kernel.org>
Delivered-To: lists+devicetree@lfdr.de
Received: from mail.lfdr.de
	by lfdr with LMTP
	id EL7dEoeq6GnEOQIAu9opvQ
	(envelope-from <devicetree+bounces-289372-lists+devicetree=lfdr.de@vger.kernel.org>)
	for <lists+devicetree@lfdr.de>; Wed, 22 Apr 2026 13:01:27 +0200
X-Original-To: lists+devicetree@lfdr.de
Received: from tor.lore.kernel.org (tor.lore.kernel.org [IPv6:2600:3c04:e001:36c::12fc:5321])
	by mail.lfdr.de (Postfix) with ESMTPS id 0CE7A4450FB
	for <lists+devicetree@lfdr.de>; Wed, 22 Apr 2026 13:01:21 +0200 (CEST)
Received: from smtp.subspace.kernel.org (conduit.subspace.kernel.org [100.90.174.1])
	by tor.lore.kernel.org (Postfix) with ESMTP id 515FB3010BBD
	for <lists+devicetree@lfdr.de>; Wed, 22 Apr 2026 11:01:20 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id 886A23CE487;
	Wed, 22 Apr 2026 11:01:19 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org;
	dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b="Y7NnjzAE"
X-Original-To: devicetree@vger.kernel.org
Received: from smtp.kernel.org (aws-us-west-2-korg-mail-1.web.codeaurora.org [10.30.226.201])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id 655A13CD8AA;
	Wed, 22 Apr 2026 11:01:19 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org; arc=none smtp.client-ip=10.30.226.201
ARC-Seal:i=1; a=rsa-sha256; d=subspace.kernel.org; s=arc-20240116;
	t=1776855679; cv=none; b=j+TlezaPvw1DIWa255I7TQ58cJkUuCV4LR41zNenNhcfi1A7H+jM9+56ycXhWGFXuAAlLZwMSaumo3EsS/UPiOUNbzjRY0dpsALKqZYppD84YqECUHtAnkGYuNT6VzvIJjmdE7lpS81CwOEdyqyAoGctzeA4eo0FvUmgA5lpBvI=
ARC-Message-Signature:i=1; a=rsa-sha256; d=subspace.kernel.org;
	s=arc-20240116; t=1776855679; c=relaxed/simple;
	bh=vSIMzTAhqwYfxZzmpkzPsQ8Ff0fX6ImiRUnKI6RL9s0=;
	h=Date:Message-ID:From:To:Cc:Subject:In-Reply-To:References:
	 MIME-Version:Content-Type; b=B6yGsgboStf6BDJh7itwMwY/UmglM74h0BlycucWYHV53LQn5/MiRgWE0Bz9S3eb+UzyJAvhLTcio72nVorupNGsOcDwMkXPA6GKwQF50b3OJf5u2fUSRzezK9PaviwOq5iYWWugBuiSO75MX/ejpNf6sMmhMKckggHj5VyVHuw=
ARC-Authentication-Results:i=1; smtp.subspace.kernel.org; dkim=pass (2048-bit key) header.d=kernel.org header.i=@kernel.org header.b=Y7NnjzAE; arc=none smtp.client-ip=10.30.226.201
Received: by smtp.kernel.org (Postfix) with ESMTPSA id 0FE54C19425;
	Wed, 22 Apr 2026 11:01:19 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=kernel.org;
	s=k20201202; t=1776855679;
	bh=vSIMzTAhqwYfxZzmpkzPsQ8Ff0fX6ImiRUnKI6RL9s0=;
	h=Date:From:To:Cc:Subject:In-Reply-To:References:From;
	b=Y7NnjzAEP8ymiska0oK+0usrDU5yq5m93mhIqgFdRBEJm0A046+BL7dOj0chcDPgH
	 pwIrygNRqZwGsSbMVRChZmrzMnJwaKyXIJB7eUS8kBlpN/5WkPj7K6IrEb6Km60ENd
	 PAdQUQ6tfvVCjSr4vuI8lGl9lc62r1SVYta2APFmez1gpG+qV+7GfXpWqzqClZUslz
	 jlpewNHUK2vGxjEBwdfkTgL1v/7QvSxnr2VEuBbDmYvStR9C7RWw29jKkuRcr8FrQ/
	 xxRrAxyT0hWBvgxPh0QJfMEc6CLKYUEvFdU4R+BhqHfsyzcLZFsfUoIWK6FUY7CTlI
	 eS7O+vC/FRyIg==
Received: from sofa.misterjones.org ([185.219.108.64] helo=goblin-girl.misterjones.org)
	by disco-boy.misterjones.org with esmtpsa  (TLS1.3) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	(Exim 4.98.2)
	(envelope-from <maz@kernel.org>)
	id 1wFVKW-0000000DiIq-4Age;
	Wed, 22 Apr 2026 11:01:17 +0000
Date: Wed, 22 Apr 2026 12:01:16 +0100
Message-ID: <86cxzr1coz.wl-maz@kernel.org>
From: Marc Zyngier <maz@kernel.org>
To: Sudeep Holla <sudeep.holla@kernel.org>
Cc: Rob Herring <robh@kernel.org>,
	Krzysztof Kozlowski <krzk+dt@kernel.org>,
	Conor Dooley <conor+dt@kernel.org>,
	devicetree@vger.kernel.org,
	linux-kernel@vger.kernel.org,
	linux-arm-kernel@lists.infradead.org
Subject: Re: [PATCH 0/5] firmware/irqchip: Add FF-A DT interrupt support for donated NS SGIs
In-Reply-To: <20260412-b4-ffa_ns_sgi_gicv3-v1-0-af61243eb405@kernel.org>
References: <20260412-b4-ffa_ns_sgi_gicv3-v1-0-af61243eb405@kernel.org>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL-LB/10.8 EasyPG/1.0.0 Emacs/30.1
 (aarch64-unknown-linux-gnu) MULE/6.0 (HANACHIRUSATO)
Precedence: bulk
X-Mailing-List: devicetree@vger.kernel.org
List-Id: <devicetree.vger.kernel.org>
List-Subscribe: <mailto:devicetree+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:devicetree+unsubscribe@vger.kernel.org>
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-SA-Exim-Connect-IP: 185.219.108.64
X-SA-Exim-Rcpt-To: sudeep.holla@kernel.org, robh@kernel.org, krzk+dt@kernel.org, conor+dt@kernel.org, devicetree@vger.kernel.org, linux-kernel@vger.kernel.org, linux-arm-kernel@lists.infradead.org
X-SA-Exim-Mail-From: maz@kernel.org
X-SA-Exim-Scanned: No (on disco-boy.misterjones.org); SAEximRunCond expanded to false
X-Spamd-Result: default: False [-1.16 / 15.00];
	ARC_ALLOW(-1.00)[subspace.kernel.org:s=arc-20240116:i=1];
	MID_CONTAINS_FROM(1.00)[];
	DMARC_POLICY_ALLOW(-0.50)[kernel.org,quarantine];
	R_SPF_ALLOW(-0.20)[+ip6:2600:3c04:e001:36c::/64:c];
	R_DKIM_ALLOW(-0.20)[kernel.org:s=k20201202];
	MAILLIST(-0.15)[generic];
	MIME_GOOD(-0.10)[text/plain];
	HAS_LIST_UNSUB(-0.01)[];
	DKIM_TRACE(0.00)[kernel.org:+];
	RCVD_TLS_LAST(0.00)[];
	FORGED_RECIPIENTS_MAILLIST(0.00)[];
	TAGGED_FROM(0.00)[bounces-289372-lists,devicetree=lfdr.de];
	MIME_TRACE(0.00)[0:+];
	FORGED_SENDER_MAILLIST(0.00)[];
	RSPAMD_EMAILBL_FAIL(0.00)[sudeep.holla.kernel.org:query timed out];
	FROM_HAS_DN(0.00)[];
	TO_DN_SOME(0.00)[];
	RCVD_COUNT_FIVE(0.00)[5];
	PRECEDENCE_BULK(0.00)[];
	FROM_NEQ_ENVFROM(0.00)[maz@kernel.org,devicetree@vger.kernel.org];
	ASN(0.00)[asn:63949, ipnet:2600:3c04::/32, country:SG];
	NEURAL_HAM(-0.00)[-1.000];
	TAGGED_RCPT(0.00)[devicetree,dt];
	RCPT_COUNT_SEVEN(0.00)[7];
	RCVD_VIA_SMTP_AUTH(0.00)[];
	DBL_BLOCKED_OPENRESOLVER(0.00)[tor.lore.kernel.org:helo,tor.lore.kernel.org:rdns]
X-Rspamd-Queue-Id: 0CE7A4450FB
X-Rspamd-Action: no action
X-Rspamd-Server: lfdr

On Sun, 12 Apr 2026 18:04:36 +0100,
Sudeep Holla <sudeep.holla@kernel.org> wrote:
>=20
> Hi all,
>=20
> This series wires FF-A notification interrupts up through DT using the
> standard interrupts property on the arm,ffa node and adds the
> required GICv3 and binding support for secure-donated non-secure SGIs.
>=20
> This has been long pending after the discussions here[1][2]. I have been
> waiting for some ACPI story to shape up for almost an year now, but no
> progress there. So posting this for now to start discussion on the approa=
ch
> taken here instead of waiting for another year to sort out ACPI =F0=9F=98=
=89.
>=20
> It:
>=20
> - documents secure-donated NS SGIs in the GIC DT binding
> - teaches the GICv3 driver to accept and map those SGIs
> - adds a DT binding for the arm,ffa firmware node
> - updates the FF-A driver to use the arm,ffa node interrupt instead of
>   synthesizing its own GIC mapping
> - adds an FVP DT node using SGI 8 as the FF-A notification interrupt
>
> The FF-A DT lookup expects a single interrupt entry, verifies that it is
> a per-CPU interrupt via the reported affinity mask, and cross-checks the
> resolved Linux IRQ hwirq against the interrupt ID returned by
> FFA_FEATURES.

I haven't looked at this in any detail, but these are the additional
issues someone needs to address:

- The GIC(v3) is dead, long live the GIC(v5)! SGIs don't exist in the
  brave new world, so FFA needs to find new ways to signal interrupts.

- FFA doesn't necessarily live in secure world, and could be
  implemented by a hypervisor. In the context of a single security
  domain machine (that's what a VM is), the guest *owns* all SGIs. So
  there is absolutely nothing to donate, and this doesn't work. FFA
  also needs fixing here.

- All of the above should work with the other firmware description
  (Avoid Critical Periodic Interrupts). But maybe FFA is not a thing
  on these machines? If not, it should be made explicit.

Overall, it only indicates that FFA should behave as a device, and
use interrupts that are valid for a device.

Thanks,

	M.

--=20
Without deviation from the norm, progress is not possible.

